services:
  MongoDB:
        image: tatum/mongodb:latest
        container_name: mongodb-zalada-billing
        ports:
          - "27019:27017"
        volumes:
          - /srv/docker/mongodb:/var/lib/mongodb
        restart: always

  billing:
        build: build/docker
        depends_on:
          - mongodb-zalada-billing
        container_name: service-billing
        restart: always
        ports:
          - 9002:9002
        links:
          - mongodb-zalada-stock